/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.portalcovidd;

import java.awt.Color;
import javax.swing.table.DefaultTableCellRenderer;
//import com.mycompany.portalcovidd.DadosPaises;
//import com.mycompany.portalcovidd.DadosVacina;
//import com.mycompany.portalcovidd.DadosMunicipais;




/**
 *
 * @author raissa
 */
public class dadosCovid extends javax.swing.JDialog {
    
    public dadosCovid(){}
    
    public int nMunicipios;
    public DadosEstados[] estados;
    
    
    private java.awt.Frame frame;
    /**
     * Creates new form dadosCovid
     */
    public dadosCovid(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.frame = parent;
        initComponents();
        tabela1.setBackground(new Color(0,0,0,0));
        ((DefaultTableCellRenderer)tabela1.getDefaultRenderer(Object.class)).setBackground(new Color(0,0,0,0));
        
        tabela1.setGridColor(Color.WHITE);
        tabela1.setForeground(Color.WHITE);
        jScrollPane1.setBackground(new Color(0,0,0,0));
        
        jScrollPane1.setOpaque(false);      
        tabela1.setOpaque(false);
        
        ((DefaultTableCellRenderer)tabela1.getDefaultRenderer(Object.class)).setOpaque(false);
        tabela1.setShowGrid(false);
        jScrollPane1.getViewport().setOpaque(false);;
        
        
        DadosEstados[] estados = ColetaDados.getCovidStatus();
        
        
        for (int i = 0; i<27; i++){
            
            tabela1.setValueAt(estados[i].state, i, 0);
            tabela1.setValueAt(estados[i].nMortes, i, 1);
            tabela1.setValueAt(estados[i].suspects, i, 2);
            tabela1.setValueAt(estados[i].nCasos, i, 3);
        }
        
//        int obitosSP = getObitosSP();
//        int recuperadosSP = getRecuperadosSP();
//        tabela1.setValueAt("Municipio", 0, 0);
//        tabela1.setValueAt(obitosSP, 0, 1);
//        tabela1.setValueAt(recuperadosSP, 0, 2);
//        Integer total = (Integer) tabela1.getValueAt(0,1) + (Integer) tabela1.getValueAt(0, 2);
//        tabela1.setValueAt(total, 0, 3);
        
    }

    
    
//    public void setTabela(DadosEstados[] dados){
//        initComponents();
//        this.estados = ColetaDados.getCovidStatus();
//
////        for(int i = 0; i < 10; i++){;
////           estados[i] = new DadosEstados(0, "0", "0", 0, 0, 0, 0, "0");
////                   
////           estados[i] = dados[i];
////
////        }
////        initComponents();
//         tabela1.setBackground(new Color(0,0,0,0));
//        ((DefaultTableCellRenderer)tabela1.getDefaultRenderer(Object.class)).setBackground(new Color(0,0,0,0));
//        
//        tabela1.setGridColor(Color.WHITE);
//        tabela1.setForeground(Color.WHITE);
//        jScrollPane1.setBackground(new Color(0,0,0,0));
//        
//        jScrollPane1.setOpaque(false);      
//        tabela1.setOpaque(false);
//        
//        ((DefaultTableCellRenderer)tabela1.getDefaultRenderer(Object.class)).setOpaque(false);
//        tabela1.setShowGrid(false);
//        jScrollPane1.getViewport().setOpaque(false);;
//        for (int i = 0; i<10; i++){
//            System.out.print("aa\n");
//            System.out.print(dados[i].deaths);
//            System.out.print(dados[i].state);
//            tabela1.setValueAt(dados[i].state, i, 0);;
//            
//        }
//    };
    
    public int getRecuperadosSP(){
        // get funcao da API
        // recuperados = funcaoAPI
        // return recuperados
        return 160;
    }
        
    public int getObitosSP(){
        // get funcao da API
        // obito = funcaoAPI
        // return obito
        return 200;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dadosCovid = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        dadosCovid.setBackground(new java.awt.Color(0, 1, 119));

        tabela1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "   Estado", "   �bitos", "   Suspeitos", "   Casos Totais"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabela1);

        javax.swing.GroupLayout dadosCovidLayout = new javax.swing.GroupLayout(dadosCovid);
        dadosCovid.setLayout(dadosCovidLayout);
        dadosCovidLayout.setHorizontalGroup(
            dadosCovidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dadosCovidLayout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(145, Short.MAX_VALUE))
        );
        dadosCovidLayout.setVerticalGroup(
            dadosCovidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dadosCovidLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dadosCovid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(dadosCovid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 59, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
           
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dadosCovid.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dadosCovid.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dadosCovid.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dadosCovid.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                dadosCovid dialog = new dadosCovid(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel dadosCovid;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable tabela1;
    // End of variables declaration//GEN-END:variables
}
